# For more information: https://laravel.com/docs/sail
version: '3'
services:
    laravel.test:
        build:
            context: ./vendor/laravel/sail/runtimes/7.4
            dockerfile: Dockerfile
            args:
                WWWGROUP: '${WWWGROUP}'
        image: sail-7.4/app
        ports:
            - '${APP_PORT:-80}:80'
        environment:
            WWWUSER: '${WWWUSER}'
            LARAVEL_SAIL: 1
        volumes:
            - '.:/var/www/html'
        networks:
            - sail
        depends_on:
            - redis
    redis:
        image: 'redis:alpine'
        ports:
            - '${FORWARD_REDIS_PORT:-6379}:6379'
        volumes:
            - 'sailredis:/data'
        networks:
            - sail
        healthcheck:
          test: ["CMD", "redis-cli", "ping"]
    queue:
        image: laravel-www
        container_name: laravel-queue
        depends_on:
          - app
        volumes:
          - .:/var/www/html
#        environment:
#          APP_ENV: local
#          CONTAINER_ROLE: queue
#          CACHE_DRIVER: redis
#          SESSION_DRIVER: redis
#          QUEUE_DRIVER: redis
#          REDIS_HOST: redis
networks:
    sail:
        driver: bridge
volumes:
    sailredis:
        driver: local
